Repository ExpectBonus/doko-yahoo, pull requests merged in 2022-06, with the labels that each got.

#22 フロントサーバの環境構築
  docker-compose.yml
  front/.gitignore
  front/Dockerfile
  front/README.md
  front/babel.config.js
  front/eslintrc.json
  front/jsconfig.json
  front/package-lock.json
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/src/App.vue
  front/src/assets/logo.png
  front/src/components/HelloWorld.vue
  front/src/main.js
  front/src/router/index.js
  front/src/store/index.js
  front/src/views/AboutView.vue
  front/src/views/HomeView.vue
  front/start.sh
  front/vue.config.js
Labels: bug

#21 環境構築
  .vscode/settings.json
  back/.gitignore
  back/Dockerfile
  back/README.md
  back/app.py
  back/config.py
  back/controllers/__init__.py
  back/controllers/comment_controller.py
  back/controllers/heatmap_controller.py
  back/controllers/user_controller.py
  back/db.py
  back/migrations/README
  back/migrations/alembic.ini
  back/migrations/env.py
  back/migrations/script.py.mako
  back/migrations/versions/4d17ec5e5d6e_.py
  back/migrations/versions/9b7bb651b83f_.py
  back/models/__init__.py
  back/models/models.py
  back/requirements.txt
  back/start.sh
  back/wsgi.py
  docker-compose.yml
  front/.gitignore
  front/Dockerfile
  front/README.md
  front/babel.config.js
  front/eslintrc.json
  front/jsconfig.json
  front/package-lock.json
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/src/App.vue
  front/src/assets/logo.png
  front/src/components/HelloWorld.vue
  front/src/main.js
  front/src/router/index.js
  front/src/store/index.js
  front/src/views/AboutView.vue
  front/src/views/HomeView.vue
  front/vue.config.js
  web/Dockerfile
Labels: enhancement

#29 ヒートマップのページを作成
  front/README.md
  front/package-lock.json
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/src/App.vue
  front/src/assets/japan_geo.json
  front/src/components/Board.vue
  front/src/components/HobbiesSelector.vue
  front/src/components/JobSelector.vue
  front/src/components/Map.vue
  front/src/main.js
  front/src/plugins/vuetify.js
  front/src/styles/reset.css
  front/src/views/MapView.vue
  front/vue.config.js
Labels: Frontend

#39 Suzuki/fix#12
  front/src/components/HobbiesSelector.vue
  front/src/components/JobSelector.vue
  front/src/views/MapView.vue
  front/src/views/ProfileView.vue
  front/src/views/prefectures.js
Labels: bug, Frontend, UI design, UseCase

#38 Yoshikawa/update#16
  front/src/components/HeatMap.vue
  front/src/components/PrefComment.vue
Labels: Frontend, UI design

#37 都道府県別掲示板の表示
  front/src/assets/japan_geo.json
  front/src/assets/send.svg
  front/src/components/Board.vue
  front/src/components/CommentsBoard.vue
  front/src/components/HeatMap.vue
  front/src/components/JobSelector.vue
  front/src/interfaces/CommentForm.vue
  front/src/views/MapView.vue
  front/vue.config.js
Labels: Frontend, UI design, UseCase

#28 フロントエンドの開発用ブランチ
  docker-compose.yml
  front/.eslintrc.json
  front/README.md
  front/eslintrc.json
  front/jsconfig.json
  front/package-lock.json
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/src/App.vue
  front/src/assets/DokoYahooLogo.png
  front/src/assets/badge.png
  front/src/assets/business_center.png
  front/src/assets/home.png
  front/src/assets/home_work.png
  front/src/assets/interests.png
  front/src/assets/japan_geo.json
  front/src/assets/logo.svg
  front/src/assets/prefectures.js
  front/src/assets/profile_icon.jpeg
  front/src/assets/send.svg
  front/src/components/CommentsBoard.vue
  front/src/components/HeatMap.vue
  front/src/components/HelloWorld.vue
  front/src/components/HobbiesSelector.vue
  front/src/components/JobSelector.vue
  front/src/components/PrefComment.vue
  front/src/interfaces/CommentForm.vue
  front/src/main.js
  front/src/router/index.js
  front/src/styles/reset.css
  front/src/views/AboutView.vue
  front/src/views/HomeView.vue
  front/src/views/MapView.vue
  front/src/views/ProfileView.vue
  front/src/views/TopView.vue
  front/vue.config.js
Labels: Frontend

#46 都道府県選択用のコンポーネントを切り分け
  front/src/components/HobbiesSelector.vue
  front/src/components/JobSelector.vue
  front/src/components/PrefSelector.vue
  front/src/views/ProfileView.vue
Labels: Frontend, UI design

#47 Frontend
  front/.env.sample
  front/.gitignore
  front/README.md
  front/package-lock.json
  front/package.json
  front/src/components/CommentsBoard.vue
  front/src/components/HobbiesSelector.vue
  front/src/components/JobSelector.vue
  front/src/components/PrefSelector.vue
  front/src/main.js
  front/src/router/index.js
  front/src/store/index.js
  front/src/styles/reset.css
  front/src/views/HomeView.vue
  front/src/views/MapView.vue
  front/src/views/ProfileView.vue
  front/src/views/TopView.vue
Labels: Frontend

#52 Arakawa/update#32
  back/.gitignore
  back/README.md
  back/app.py
  back/controllers/user_controller.py
  back/requirements.txt
  back/swagger.yml
  back/test/user_test.py
Labels: Backend
